# Site settings
title: Grupo Scout VatnajokÃ¼ll
email: gsvatnajokull@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "gsvatnajokull.github.io" # the base hostname & protocol for your site

twitter_username: gsvatnajokull
github_username: gsvatnajokull

# Build settings
markdown: kramdown
